# Generated by Django 4.0.5 on 2022-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=1),
        ),
    ]
